import { Leaf, Droplet, Bug, Tractor, Wheat, Sprout, Flower, Zap, Thermometer } from "lucide-react"
import type { Product } from "@/lib/types"

// Categories data
export const categories = [
  {
    id: "seeds",
    name: "Seeds",
    icon: <Wheat className="h-12 w-12" />,
    description: "High-quality seeds for various crops with excellent germination rates",
    color: "bg-green-100 dark:bg-green-900",
    textColor: "text-green-700 dark:text-green-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Wheat Seeds", count: 12 },
      { name: "Rice Seeds", count: 15 },
      { name: "Corn Seeds", count: 8 },
      { name: "Vegetable Seeds", count: 24 },
      { name: "Fruit Seeds", count: 10 },
      { name: "Cotton Seeds", count: 6 },
    ],
  },
  {
    id: "fertilizers",
    name: "Fertilizers",
    icon: <Leaf className="h-12 w-12" />,
    description: "Organic and chemical fertilizers to enhance soil fertility and crop yield",
    color: "bg-blue-100 dark:bg-blue-900",
    textColor: "text-blue-700 dark:text-blue-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Organic Fertilizers", count: 18 },
      { name: "NPK Fertilizers", count: 14 },
      { name: "Micronutrients", count: 9 },
      { name: "Biofertilizers", count: 7 },
      { name: "Liquid Fertilizers", count: 11 },
    ],
  },
  {
    id: "pesticides",
    name: "Pesticides",
    icon: <Bug className="h-12 w-12" />,
    description: "Effective pest control solutions to protect your crops from harmful insects",
    color: "bg-red-100 dark:bg-red-900",
    textColor: "text-red-700 dark:text-red-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Insecticides", count: 16 },
      { name: "Fungicides", count: 12 },
      { name: "Herbicides", count: 9 },
      { name: "Organic Pesticides", count: 8 },
      { name: "Rodenticides", count: 5 },
    ],
  },
  {
    id: "equipment",
    name: "Equipment",
    icon: <Tractor className="h-12 w-12" />,
    description: "Modern farming equipment and tools to increase efficiency and productivity",
    color: "bg-amber-100 dark:bg-amber-900",
    textColor: "text-amber-700 dark:text-amber-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Tractors & Accessories", count: 8 },
      { name: "Hand Tools", count: 22 },
      { name: "Sprayers", count: 14 },
      { name: "Harvesting Equipment", count: 9 },
      { name: "Plows & Tillers", count: 11 },
      { name: "Storage Equipment", count: 7 },
    ],
  },
  {
    id: "irrigation",
    name: "Irrigation",
    icon: <Droplet className="h-12 w-12" />,
    description: "Water-efficient irrigation systems for optimal water management",
    color: "bg-cyan-100 dark:bg-cyan-900",
    textColor: "text-cyan-700 dark:text-cyan-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Drip Irrigation", count: 15 },
      { name: "Sprinkler Systems", count: 12 },
      { name: "Water Pumps", count: 9 },
      { name: "Pipes & Fittings", count: 24 },
      { name: "Water Tanks", count: 8 },
      { name: "Irrigation Controllers", count: 6 },
    ],
  },
  {
    id: "organic",
    name: "Organic",
    icon: <Sprout className="h-12 w-12" />,
    description: "Certified organic products for sustainable and chemical-free farming",
    color: "bg-emerald-100 dark:bg-emerald-900",
    textColor: "text-emerald-700 dark:text-emerald-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Organic Seeds", count: 18 },
      { name: "Organic Fertilizers", count: 14 },
      { name: "Organic Pesticides", count: 9 },
      { name: "Organic Soil Amendments", count: 11 },
      { name: "Organic Certification", count: 3 },
    ],
  },
  {
    id: "horticulture",
    name: "Horticulture",
    icon: <Flower className="h-12 w-12" />,
    description: "Specialized products for fruit, vegetable, and ornamental plant cultivation",
    color: "bg-pink-100 dark:bg-pink-900",
    textColor: "text-pink-700 dark:text-pink-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Greenhouse Supplies", count: 12 },
      { name: "Grafting Tools", count: 8 },
      { name: "Plant Growth Regulators", count: 6 },
      { name: "Nursery Containers", count: 15 },
      { name: "Pruning Tools", count: 9 },
    ],
  },
  {
    id: "livestock",
    name: "Livestock",
    icon: <Zap className="h-12 w-12" />,
    description: "Products for animal husbandry and livestock management",
    color: "bg-orange-100 dark:bg-orange-900",
    textColor: "text-orange-700 dark:text-orange-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Animal Feed", count: 16 },
      { name: "Veterinary Supplies", count: 12 },
      { name: "Housing Equipment", count: 8 },
      { name: "Breeding Supplies", count: 5 },
      { name: "Dairy Equipment", count: 7 },
    ],
  },
  {
    id: "climate-control",
    name: "Climate Control",
    icon: <Thermometer className="h-12 w-12" />,
    description: "Solutions for managing climate conditions in farms and greenhouses",
    color: "bg-purple-100 dark:bg-purple-900",
    textColor: "text-purple-700 dark:text-purple-300",
    image: "/placeholder.svg?height=300&width=300",
    subcategories: [
      { name: "Greenhouse Heaters", count: 8 },
      { name: "Cooling Systems", count: 7 },
      { name: "Humidity Controllers", count: 5 },
      { name: "Weather Stations", count: 4 },
      { name: "Shade Systems", count: 6 },
    ],
  },
]

// Helper function to get category by ID
export function getCategoryById(id: string) {
  return categories.find((category) => category.id === id)
}

// Products data with expanded dataset
export const products: Product[] = [
  // Seeds Category
  {
    id: "seed-1",
    name: "Premium Wheat Seeds",
    description: "High-yield wheat seeds for optimal crop production",
    price: 499,
    image: "/placeholder.svg?height=200&width=200",
    category: "Seeds",
    subcategory: "Wheat Seeds",
    rating: 4.8,
    reviews: 124,
    isNew: true,
    isBestSeller: false,
    brand: "AgTech Solutions",
    features: [
      "High germination rate (95%+)",
      "Disease resistant variety",
      "Suitable for all soil types",
      "Drought tolerant",
      "High yield potential (40-45 quintals per acre)",
    ],
  },
  {
    id: "seed-2",
    name: "Organic Rice Seeds",
    description: "Certified organic rice seeds for chemical-free farming",
    price: 549,
    image: "/placeholder.svg?height=200&width=200",
    category: "Seeds",
    subcategory: "Rice Seeds",
    rating: 4.7,
    reviews: 98,
    isNew: false,
    isBestSeller: true,
    brand: "GreenLife",
    features: [
      "100% organic certified",
      "High yield potential",
      "Disease resistant",
      "Aromatic variety",
      "Suitable for various soil conditions",
    ],
  },
  {
    id: "seed-3",
    name: "Hybrid Corn Seeds",
    description: "High-yielding hybrid corn seeds with excellent vigor",
    price: 399,
    image: "/placeholder.svg?height=200&width=200",
    category: "Seeds",
    subcategory: "Corn Seeds",
    rating: 4.6,
    reviews: 87,
    isNew: false,
    isBestSeller: false,
    brand: "CropMaster",
    features: [
      "Early maturing variety",
      "Drought resistant",
      "High starch content",
      "Excellent for silage",
      "Resistant to common corn diseases",
    ],
  },
  {
    id: "seed-4",
    name: "Vegetable Seed Kit",
    description: "Assorted vegetable seeds for home gardens and small farms",
    price: 299,
    image: "/placeholder.svg?height=200&width=200",
    category: "Seeds",
    subcategory: "Vegetable Seeds",
    rating: 4.5,
    reviews: 112,
    isNew: true,
    isBestSeller: false,
    brand: "AgTech Solutions",
    features: [
      "10 different vegetable varieties",
      "High germination rate",
      "Detailed growing instructions included",
      "Non-GMO varieties",
      "Suitable for container gardening",
    ],
  },
  {
    id: "seed-5",
    name: "Cotton Seeds",
    description: "Premium cotton seeds for commercial cultivation",
    price: 649,
    image: "/placeholder.svg?height=200&width=200",
    category: "Seeds",
    subcategory: "Cotton Seeds",
    rating: 4.4,
    reviews: 76,
    isNew: false,
    isBestSeller: false,
    brand: "FarmEx",
    features: [
      "High fiber quality",
      "Pest resistant variety",
      "Suitable for various soil types",
      "Drought tolerant",
      "High yield potential",
    ],
  },

  // Fertilizers Category
  {
    id: "fert-1",
    name: "Organic Compost",
    description: "Nutrient-rich organic compost for soil enrichment",
    price: 299,
    image: "/placeholder.svg?height=200&width=200",
    category: "Fertilizers",
    subcategory: "Organic Fertilizers",
    rating: 4.6,
    reviews: 89,
    isNew: false,
    isBestSeller: true,
    brand: "GreenLife",
    features: [
      "100% organic certified",
      "Improves soil structure",
      "Slow-release nutrients",
      "Enhances microbial activity",
      "Suitable for all crops",
    ],
  },
  {
    id: "fert-2",
    name: "NPK Fertilizer 20-20-20",
    description: "Balanced NPK fertilizer for overall plant growth",
    price: 449,
    image: "/placeholder.svg?height=200&width=200",
    category: "Fertilizers",
    subcategory: "NPK Fertilizers",
    rating: 4.7,
    reviews: 104,
    isNew: false,
    isBestSeller: false,
    brand: "AgTech Solutions",
    features: [
      "Balanced nutrient formula",
      "Quick nutrient availability",
      "Suitable for all growth stages",
      "Water-soluble granules",
      "Enhances flowering and fruiting",
    ],
  },
  {
    id: "fert-3",
    name: "Micronutrient Mix",
    description: "Essential micronutrients to prevent deficiencies",
    price: 349,
    image: "/placeholder.svg?height=200&width=200",
    category: "Fertilizers",
    subcategory: "Micronutrients",
    rating: 4.5,
    reviews: 67,
    isNew: true,
    isBestSeller: false,
    brand: "SoilRich",
    features: [
      "Contains zinc, boron, manganese, and iron",
      "Chelated formulation for better absorption",
      "Prevents yellowing and stunted growth",
      "Foliar application compatible",
      "Enhances crop quality",
    ],
  },
  {
    id: "fert-4",
    name: "Biofertilizer Pack",
    description: "Beneficial microorganisms to enhance soil fertility",
    price: 279,
    image: "/placeholder.svg?height=200&width=200",
    category: "Fertilizers",
    subcategory: "Biofertilizers",
    rating: 4.3,
    reviews: 58,
    isNew: false,
    isBestSeller: false,
    brand: "GreenLife",
    features: [
      "Contains nitrogen-fixing bacteria",
      "Improves nutrient availability",
      "Enhances root development",
      "Reduces chemical fertilizer dependency",
      "Eco-friendly solution",
    ],
  },

  // Pesticides Category
  {
    id: "pest-1",
    name: "Bio Pesticide",
    description: "Eco-friendly pesticide for pest control",
    price: 599,
    image: "/placeholder.svg?height=200&width=200",
    category: "Pesticides",
    subcategory: "Organic Pesticides",
    rating: 4.5,
    reviews: 76,
    isNew: false,
    isBestSeller: false,
    brand: "GreenLife",
    features: [
      "Neem-based formulation",
      "Controls wide range of pests",
      "Safe for beneficial insects",
      "No harmful residues",
      "Suitable for organic farming",
    ],
  },
  {
    id: "pest-2",
    name: "Broad Spectrum Insecticide",
    description: "Effective control against multiple insect pests",
    price: 499,
    image: "/placeholder.svg?height=200&width=200",
    category: "Pesticides",
    subcategory: "Insecticides",
    rating: 4.4,
    reviews: 82,
    isNew: false,
    isBestSeller: true,
    brand: "CropMaster",
    features: [
      "Fast-acting formula",
      "Rainfast within 2 hours",
      "Controls chewing and sucking insects",
      "Long residual activity",
      "Low odor formulation",
    ],
  },
  {
    id: "pest-3",
    name: "Fungicide Solution",
    description: "Prevents and treats fungal diseases in crops",
    price: 449,
    image: "/placeholder.svg?height=200&width=200",
    category: "Pesticides",
    subcategory: "Fungicides",
    rating: 4.6,
    reviews: 64,
    isNew: true,
    isBestSeller: false,
    brand: "AgTech Solutions",
    features: [
      "Broad-spectrum disease control",
      "Preventive and curative action",
      "Systemic and contact protection",
      "Rainfast formulation",
      "Compatible with most pesticides",
    ],
  },

  // Equipment Category
  {
    id: "equip-1",
    name: "Hand Tiller",
    description: "Durable hand tiller for small farms",
    price: 1299,
    image: "/placeholder.svg?height=200&width=200",
    category: "Equipment",
    subcategory: "Hand Tools",
    rating: 4.7,
    reviews: 52,
    isNew: true,
    isBestSeller: false,
    brand: "FarmEx",
    features: [
      "Ergonomic design",
      "Durable steel construction",
      "Adjustable tilling width",
      "Comfortable grip handles",
      "Lightweight and easy to use",
    ],
  },
  {
    id: "equip-2",
    name: "Backpack Sprayer",
    description: "High-capacity backpack sprayer for efficient application",
    price: 1899,
    image: "/placeholder.svg?height=200&width=200",
    category: "Equipment",
    subcategory: "Sprayers",
    rating: 4.8,
    reviews: 73,
    isNew: false,
    isBestSeller: true,
    brand: "AgTech Solutions",
    features: [
      "16L capacity tank",
      "Adjustable pressure control",
      "Multiple nozzle options included",
      "Comfortable padded straps",
      "Chemical-resistant components",
    ],
  },
  {
    id: "equip-3",
    name: "Mini Rotary Tiller",
    description: "Compact rotary tiller for small to medium farms",
    price: 24999,
    image: "/placeholder.svg?height=200&width=200",
    category: "Equipment",
    subcategory: "Plows & Tillers",
    rating: 4.6,
    reviews: 38,
    isNew: false,
    isBestSeller: false,
    brand: "FarmEx",
    features: [
      "5.5 HP engine",
      "Adjustable tilling width (30-60cm)",
      "Adjustable tilling depth",
      "Forward and reverse gears",
      "Foldable handles for storage",
    ],
  },

  // Irrigation Category
  {
    id: "irr-1",
    name: "Drip Irrigation Kit",
    description: "Water-saving drip irrigation system for efficient farming",
    price: 2499,
    image: "/placeholder.svg?height=200&width=200",
    category: "Irrigation",
    subcategory: "Drip Irrigation",
    rating: 4.9,
    reviews: 38,
    isNew: true,
    isBestSeller: false,
    brand: "AgTech Solutions",
    features: [
      "Complete kit for 1/4 acre",
      "Water-saving design",
      "UV-resistant components",
      "Easy installation",
      "Includes filters and pressure regulators",
    ],
  },
  {
    id: "irr-2",
    name: "Sprinkler System",
    description: "Efficient sprinkler system for even water distribution",
    price: 1899,
    image: "/placeholder.svg?height=200&width=200",
    category: "Irrigation",
    subcategory: "Sprinkler Systems",
    rating: 4.7,
    reviews: 45,
    isNew: false,
    isBestSeller: true,
    brand: "FarmEx",
    features: [
      "360° coverage",
      "Adjustable spray distance",
      "Durable plastic construction",
      "Easy to install and maintain",
      "Compatible with standard hose connections",
    ],
  },
]

// Helper function to get products by category
export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(
    (product) => product.category.toLowerCase() === getCategoryById(categoryId)?.name.toLowerCase(),
  )
}

// Helper function to get products by subcategory
export function getProductsBySubcategory(subcategory: string): Product[] {
  return products.filter((product) => product.subcategory === subcategory)
}

// Helper function to get related products
export function getRelatedProducts(productId: string, limit = 4): Product[] {
  const currentProduct = products.find((p) => p.id === productId)
  if (!currentProduct) return []

  return products.filter((p) => p.category === currentProduct.category && p.id !== productId).slice(0, limit)
}

